"""Tests for protofx.ir.Graph — graph-owned mutable IR."""

import numpy as np
import pytest

from protofx.ir import DType, TensorType
from protofx.ir.graph import Graph
from protofx.ir.value import ValueKind


class TestGraphConstruction:
    """Verify Graph can be constructed with expected fields."""

    def test_empty_graph(self) -> None:
        """An empty Graph has no inputs, outputs, or nodes."""
        g = Graph()
        assert g.inputs == []
        assert g.outputs == []
        assert g.nodes == []

    def test_name_default_none(self) -> None:
        """Graph name defaults to None."""
        g = Graph()
        assert g.name is None

    def test_name_set(self) -> None:
        """Graph name can be explicitly set."""
        g = Graph(name="main")
        assert g.name == "main"

    def test_parent_default_none(self) -> None:
        """Parent defaults to None for top-level graphs."""
        g = Graph()
        assert g.parent is None

    def test_parent_can_be_set(self) -> None:
        """Parent can be set to another Graph for subgraph support."""
        parent = Graph(name="outer")
        child = Graph(name="inner", parent=parent)
        assert child.parent is parent

    def test_values_registry_empty(self) -> None:
        """Internal value registry starts empty."""
        g = Graph()
        assert g.value_count == 0

    def test_node_count_empty(self) -> None:
        """Internal node count starts at zero."""
        g = Graph()
        assert g.node_count == 0


# ---------------------------------------------------------------------------
# Graph.add_input
# ---------------------------------------------------------------------------


class TestGraphAddInput:
    """Verify Graph.add_input creates and registers a GRAPH_INPUT Value."""

    def test_returns_value(self) -> None:
        """add_input must return a Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        assert v is not None

    def test_value_kind_is_graph_input(self) -> None:
        """Returned Value must have GRAPH_INPUT kind."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.kind == ValueKind.GRAPH_INPUT

    def test_value_has_auto_id(self) -> None:
        """Value id is auto-generated by Graph."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert isinstance(v.id, str)
        assert len(v.id) > 0

    def test_value_registered_in_inputs(self) -> None:
        """Value is appended to graph.inputs."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v in g.inputs

    def test_value_registered_in_values(self) -> None:
        """Value is registered in the internal value registry."""
        g = Graph()
        g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert g.value_count == 1

    def test_auto_id_increments(self) -> None:
        """Each add_input produces a distinct id."""
        g = Graph()
        v0 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        v1 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v0.id != v1.id

    def test_name_preserved(self) -> None:
        """Optional name is stored on the Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), name="input_0")
        assert v.name == "input_0"

    def test_producer_is_none(self) -> None:
        """Graph inputs have no producer."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.producer is None

    def test_users_empty(self) -> None:
        """Newly created input has no users."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.users == ()


# ---------------------------------------------------------------------------
# Graph.make_node
# ---------------------------------------------------------------------------


class TestGraphMakeNode:
    """Verify Graph.make_node creates a Node with outputs and use-def links."""

    def test_returns_node(self) -> None:
        """make_node must return a Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2, 3))],
        )
        assert node is not None

    def test_node_has_auto_id(self) -> None:
        """Node id is auto-generated by Graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert isinstance(node.id, str)
        assert len(node.id) > 0

    def test_node_registered_in_nodes(self) -> None:
        """Node is appended to graph.nodes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert node in g.nodes

    def test_node_registered_in_registry(self) -> None:
        """Node is registered in the internal node registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert g.node_count == 1

    def test_outputs_created(self) -> None:
        """Node outputs are auto-created as Value instances."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(node.outputs) == 1
        assert node.outputs[0].kind == ValueKind.NODE_OUTPUT

    def test_output_producer_set(self) -> None:
        """Each output Value's producer must point to the created Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.outputs[0].producer is node

    def test_output_values_registered(self) -> None:
        """Output Values are registered in the graph's value registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        # 1 input + 1 output = 2 values
        assert g.value_count == 2

    def test_input_users_updated(self) -> None:
        """Creating a node updates users on each input Value."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(inp.users) == 1
        assert inp.users[0] == (node, 0)

    def test_multi_input_users(self) -> None:
        """Each input Value gets the correct (node, slot) entry."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, b], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert a.users[0] == (node, 0)
        assert b.users[0] == (node, 1)

    def test_multi_output_node(self) -> None:
        """A node with multiple outputs produces one Value per output."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)))
        node = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
            ],
        )
        assert len(node.outputs) == 2
        assert node.outputs[0].producer is node
        assert node.outputs[1].producer is node

    def test_node_inputs_reference(self) -> None:
        """node.inputs stores references to the input Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.inputs == (inp,)

    def test_chained_nodes(self) -> None:
        """Output of one node can be input to another; use-def chain."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        assert n1.outputs[0].users[0] == (n2, 0)
        assert n2.inputs[0].producer is n1

    def test_attributes_forwarded(self) -> None:
        """Attributes are stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1, 3, 224, 224)))
        node = g.make_node(
            op_type="Conv",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1, 64, 112, 112))],
            attributes={"kernel_shape": [7, 7], "strides": [2, 2]},
        )
        assert node.attributes == {"kernel_shape": [7, 7], "strides": [2, 2]}

    def test_domain_forwarded(self) -> None:
        """Domain is stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="CustomOp",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            domain="com.custom",
        )
        assert node.domain == "com.custom"

    def test_name_forwarded(self) -> None:
        """Optional node name is stored."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            name="relu_0",
        )
        assert node.name == "relu_0"

    def test_output_names_forwarded(self) -> None:
        """Optional output names are stored on output Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
            output_names=["relu_out"],
        )
        assert node.outputs[0].name == "relu_out"


# ---------------------------------------------------------------------------
# Graph.set_node_inputs — atomic input rewiring
# ---------------------------------------------------------------------------


class TestGraphSetNodeInputs:
    """Verify set_node_inputs atomically rewires use-def links.

    Atomic order:
    1. Remove old users entries from old input Values.
    2. Replace node.inputs.
    3. Add new users entries to new input Values.
    """

    def test_basic_rewire(self) -> None:
        """Replace single input — old users cleared, new users added."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(node, [b])
        assert node.inputs == (b,)
        assert len(a.users) == 0
        assert b.users[0] == (node, 0)

    def test_multi_input_rewire(self) -> None:
        """Replace both inputs of a binary op."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        c = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        d = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, b], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(node, [c, d])
        assert len(a.users) == 0
        assert len(b.users) == 0
        assert c.users[0] == (node, 0)
        assert d.users[0] == (node, 1)

    def test_rewire_preserves_other_users(self) -> None:
        """Rewiring one node does not affect another node using the same value."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(op_type="Sigmoid", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(n1, [b])
        # n2 still uses a
        assert any(u[0] is n2 for u in a.users)
        assert not any(u[0] is n1 for u in a.users)

    def test_same_value_multiple_slots(self) -> None:
        """A value used in multiple input slots gets entries for each."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(a.users) == 2
        g.set_node_inputs(node, [a])
        assert len(a.users) == 1
        assert a.users[0] == (node, 0)


# ---------------------------------------------------------------------------
# Graph.set_value_type — update tensor metadata
# ---------------------------------------------------------------------------


class TestGraphSetValueType:
    """Verify set_value_type updates tensor metadata on a Value."""

    def test_update_tensor_type(self) -> None:
        """Tensor type is replaced."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        new_tt = TensorType(dtype=DType.FLOAT16, shape=(2, 3))
        g.set_value_type(v, new_tt)
        assert v.tensor_type is new_tt

    def test_original_unchanged_reference(self) -> None:
        """The original TensorType object is not mutated."""
        g = Graph()
        original_tt = TensorType(dtype=DType.FLOAT32, shape=(2,))
        v = g.add_input(tensor_type=original_tt)
        new_tt = TensorType(dtype=DType.INT64, shape=(2,))
        g.set_value_type(v, new_tt)
        assert original_tt.dtype == DType.FLOAT32


# ---------------------------------------------------------------------------
# Graph.set_graph_outputs
# ---------------------------------------------------------------------------


class TestGraphSetGraphOutputs:
    """Verify set_graph_outputs sets graph.outputs properly."""

    def test_set_outputs(self) -> None:
        """Graph outputs are set to the provided values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_graph_outputs([node.outputs[0]])
        assert g.outputs == [node.outputs[0]]

    def test_set_multiple_outputs(self) -> None:
        """Multiple outputs can be set."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)))
        node = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
            ],
        )
        g.set_graph_outputs([node.outputs[0], node.outputs[1]])
        assert len(g.outputs) == 2

    def test_replace_outputs(self) -> None:
        """Setting outputs replaces previous outputs."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        g.set_graph_outputs([n1.outputs[0]])
        assert g.outputs == [n1.outputs[0]]
        g.set_graph_outputs([n2.outputs[0]])
        assert g.outputs == [n2.outputs[0]]


# ---------------------------------------------------------------------------
# Graph.remove_node — fast-fail if outputs in use
# ---------------------------------------------------------------------------


class TestGraphRemoveNode:
    """Verify remove_node deletes a node and cleans up use-def links."""

    def test_remove_unused_node(self) -> None:
        """Remove a node whose outputs have no consumers."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.remove_node(node)
        assert node not in g.nodes
        assert g.node_count == 0

    def test_remove_cleans_input_users(self) -> None:
        """Removing a node clears its entries from input Value users."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.remove_node(node)
        assert len(inp.users) == 0

    def test_remove_unregisters_output_values(self) -> None:
        """Removing a node unregisters its output Values from the graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert g.value_count == 2
        g.remove_node(g.nodes[0])
        assert g.value_count == 1

    def test_remove_refuses_if_output_in_use(self) -> None:
        """remove_node raises ValueError if any output has consumers."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        with pytest.raises(ValueError, match="in use"):
            g.remove_node(n1)

    def test_remove_refuses_preserves_state(self) -> None:
        """After a refused removal, the graph is unchanged."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        try:
            g.remove_node(n1)
        except ValueError:
            pass
        assert n1 in g.nodes
        assert g.node_count == 2


class TestGraphTopologicalSort:
    """Tests for Graph.topological_sort — Kahn's algorithm & cycle detection."""

    def test_empty_graph(self) -> None:
        """Topological sort on an empty graph returns an empty list."""
        g = Graph()
        assert g.topological_sort() == []

    def test_single_node(self) -> None:
        """Single-node graph returns that node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        result = g.topological_sort()
        assert result == [n1]

    def test_linear_chain(self) -> None:
        """Linear chain: A -> B -> C returns [A, B, C]."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        n3 = g.make_node(
            op_type="Tanh", inputs=[n2.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        result = g.topological_sort()
        assert result == [n1, n2, n3]

    def test_diamond_dag(self) -> None:
        """Diamond DAG: predecessors appear before dependents."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(op_type="Sigmoid", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n3 = g.make_node(
            op_type="Add",
            inputs=[n1.outputs[0], n2.outputs[0]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        result = g.topological_sort()
        # n3 must come after both n1 and n2
        assert result.index(n3) > result.index(n1)
        assert result.index(n3) > result.index(n2)
        assert len(result) == 3

    def test_returns_new_list(self) -> None:
        """topological_sort returns a freshly allocated list, not graph.nodes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        result = g.topological_sort()
        assert result is not g.nodes

    def test_cycle_detection_raises(self) -> None:
        """A graph with a cycle in Node inputs raises ValueError."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        # Force a cycle: make n1 depend on n2's output
        g.set_node_inputs(n1, [n2.outputs[0]])
        with pytest.raises(ValueError, match="cycle"):
            g.topological_sort()

    def test_multi_output_node_ordering(self) -> None:
        """Node with multiple outputs: dependents come after the producer."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(4,)))
        n_split = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,)), TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        n_a = g.make_node(
            op_type="Relu",
            inputs=[n_split.outputs[0]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        n_b = g.make_node(
            op_type="Sigmoid",
            inputs=[n_split.outputs[1]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        result = g.topological_sort()
        assert result.index(n_split) < result.index(n_a)
        assert result.index(n_split) < result.index(n_b)


class TestGraphValidate:
    """Tests for Graph.validate — IR invariant checking."""

    def test_valid_graph_passes(self) -> None:
        """A correctly constructed graph passes validation."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_graph_outputs([n1.outputs[0]])
        g.validate()  # should not raise

    def test_empty_graph_passes(self) -> None:
        """An empty graph passes validation."""
        g = Graph()
        g.validate()  # should not raise

    def test_detects_broken_producer(self) -> None:
        """Fails if a node output's producer does not point back to the node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: set _producer to None directly (bypassing read-only property)
        n1.outputs[0]._producer = None
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_detects_broken_user_backref(self) -> None:
        """Fails if a value's users list is inconsistent with node.inputs."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: add a fake user entry
        from protofx.ir.node import Node

        fake_node = Node(id="fake", op_type="Fake")
        n1.outputs[0]._users.append((fake_node, 0))
        with pytest.raises(ValueError, match="user"):
            g.validate()

    def test_detects_unregistered_input_value(self) -> None:
        """Fails if a node references an input value not in the graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: replace input with an unregistered value
        from protofx.ir.value import Value

        rogue = Value(id="rogue", kind=ValueKind.GRAPH_INPUT, tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1._inputs[0] = rogue
        with pytest.raises(ValueError, match="not registered"):
            g.validate()

    def test_detects_cycle(self) -> None:
        """Validation catches cycles via topological sort."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        g.set_node_inputs(n1, [n2.outputs[0]])
        with pytest.raises(ValueError, match="cycle"):
            g.validate()


class TestGraphValidateTightened:
    """Tests for tightened Graph.validate — kind-specific producer rules, outputs, ownership."""

    def test_sentinel_with_producer_fails(self) -> None:
        """SENTINEL values must have producer=None; corrupt producer must fail."""
        g = Graph()
        s = g.add_sentinel()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: give sentinel a producer
        s._producer = node
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_constant_with_producer_fails(self) -> None:
        """CONSTANT values created via add_constant must have producer=None."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        c = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: give constant a producer
        c._producer = node
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_initializer_with_producer_fails(self) -> None:
        """INITIALIZER values must have producer=None."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        init = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt
        init._producer = node
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_graph_input_with_producer_fails(self) -> None:
        """GRAPH_INPUT values must have producer=None."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt
        inp._producer = node
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_node_output_without_producer_fails(self) -> None:
        """NODE_OUTPUT values must have a producer."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: remove producer
        node.outputs[0]._producer = None
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_graph_output_not_registered_fails(self) -> None:
        """Graph outputs must be registered values."""
        from protofx.ir.value import Value

        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        rogue = Value(id="rogue", kind=ValueKind.NODE_OUTPUT, tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.outputs = [rogue]
        with pytest.raises(ValueError, match="output.*not registered"):
            g.validate()

    def test_initializer_not_in_list_fails(self) -> None:
        """An INITIALIZER value must appear in graph.initializers."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        init = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        # Corrupt: remove from initializers list but keep registered
        g.initializers.remove(init)
        with pytest.raises(ValueError, match="initializer.*not in.*initializers"):
            g.validate()

    def test_graph_input_not_in_inputs_list_fails(self) -> None:
        """A GRAPH_INPUT value must appear in graph.inputs."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        # Corrupt: remove from inputs list but keep registered
        g.inputs.remove(inp)
        with pytest.raises(ValueError, match="input.*not in.*inputs"):
            g.validate()

    def test_valid_graph_with_special_values_passes(self) -> None:
        """A correctly constructed graph with sentinel, constant, and initializer passes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        w = g.add_initializer(
            tensor_type=TensorType(dtype=DType.FLOAT32, shape=(3, 4)),
            data=np.zeros((3, 4), dtype=np.float32),
        )
        _s = g.add_sentinel()
        _c = g.add_constant(
            tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)),
            data=np.array([1.0], dtype=np.float32),
        )
        node = g.make_node(
            op_type="MatMul",
            inputs=[inp, w],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2, 4))],
        )
        g.set_graph_outputs([node.outputs[0]])
        g.validate()  # should not raise


# ---------------------------------------------------------------------------
# Graph.initializers field
# ---------------------------------------------------------------------------


class TestGraphInitializersField:
    """Verify Graph exposes a public ``initializers`` list."""

    def test_initializers_default_empty(self) -> None:
        """A new Graph has an empty initializers list."""
        g = Graph()
        assert g.initializers == []

    def test_initializers_is_list(self) -> None:
        """Graph.initializers is a list."""
        g = Graph()
        assert isinstance(g.initializers, list)


# ---------------------------------------------------------------------------
# Graph.add_sentinel
# ---------------------------------------------------------------------------


class TestGraphAddSentinel:
    """Verify Graph.add_sentinel creates a SENTINEL Value."""

    def test_returns_value(self) -> None:
        """add_sentinel must return a Value."""
        g = Graph()
        v = g.add_sentinel()
        assert v is not None

    def test_kind_is_sentinel(self) -> None:
        """Returned Value must have SENTINEL kind."""
        g = Graph()
        v = g.add_sentinel()
        assert v.kind == ValueKind.SENTINEL

    def test_tensor_type_unknown(self) -> None:
        """Sentinel has unknown tensor metadata (dtype=None, shape=None)."""
        g = Graph()
        v = g.add_sentinel()
        assert v.tensor_type.dtype is None
        assert v.tensor_type.shape is None

    def test_producer_is_none(self) -> None:
        """Sentinel values have no producer."""
        g = Graph()
        v = g.add_sentinel()
        assert v.producer is None

    def test_data_is_none(self) -> None:
        """Sentinel values carry no data payload."""
        g = Graph()
        v = g.add_sentinel()
        assert v.data is None

    def test_registered_in_values(self) -> None:
        """Sentinel is registered in the graph's value registry."""
        g = Graph()
        g.add_sentinel()
        assert g.value_count == 1

    def test_not_in_inputs(self) -> None:
        """Sentinel does not appear in graph.inputs."""
        g = Graph()
        g.add_sentinel()
        assert g.inputs == []

    def test_not_in_initializers(self) -> None:
        """Sentinel does not appear in graph.initializers."""
        g = Graph()
        g.add_sentinel()
        assert g.initializers == []

    def test_each_call_creates_new_instance(self) -> None:
        """Each add_sentinel call produces a distinct Value."""
        g = Graph()
        s1 = g.add_sentinel()
        s2 = g.add_sentinel()
        assert s1 is not s2
        assert s1.id != s2.id

    def test_auto_id(self) -> None:
        """Sentinel gets an auto-generated id."""
        g = Graph()
        v = g.add_sentinel()
        assert isinstance(v.id, str)
        assert len(v.id) > 0


# ---------------------------------------------------------------------------
# Graph.add_constant
# ---------------------------------------------------------------------------


class TestGraphAddConstant:
    """Verify Graph.add_constant creates a CONSTANT Value with data."""

    def test_returns_value(self) -> None:
        """add_constant must return a Value."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert v is not None

    def test_kind_is_constant(self) -> None:
        """Returned Value must have CONSTANT kind."""
        g = Graph()
        arr = np.array([1.0, 2.0], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)), data=arr)
        assert v.kind == ValueKind.CONSTANT

    def test_data_stored(self) -> None:
        """The numpy array is stored on the Value."""
        g = Graph()
        arr = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 2)), data=arr)
        assert v.data is arr

    def test_tensor_type_stored(self) -> None:
        """The tensor type is stored on the Value."""
        g = Graph()
        arr = np.array([0.5], dtype=np.float32)
        tt = TensorType(dtype=DType.FLOAT32, shape=(1,))
        v = g.add_constant(tensor_type=tt, data=arr)
        assert v.tensor_type is tt

    def test_producer_is_none(self) -> None:
        """Constant values created by add_constant have no producer."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert v.producer is None

    def test_name_preserved(self) -> None:
        """Optional name is stored on the Value."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr, name="const_0")
        assert v.name == "const_0"

    def test_registered_in_values(self) -> None:
        """Constant is registered in the graph's value registry."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert g.value_count == 1

    def test_not_in_inputs(self) -> None:
        """Constant does not appear in graph.inputs."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert g.inputs == []

    def test_not_in_initializers(self) -> None:
        """Constant does not appear in graph.initializers."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert g.initializers == []

    def test_auto_id(self) -> None:
        """Constant gets an auto-generated id."""
        g = Graph()
        arr = np.array([1.0], dtype=np.float32)
        v = g.add_constant(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), data=arr)
        assert isinstance(v.id, str)
        assert len(v.id) > 0


# ---------------------------------------------------------------------------
# Graph.add_initializer
# ---------------------------------------------------------------------------


class TestGraphAddInitializer:
    """Verify Graph.add_initializer creates an INITIALIZER Value with data."""

    def test_returns_value(self) -> None:
        """add_initializer must return a Value."""
        g = Graph()
        arr = np.zeros((64, 3, 7, 7), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(64, 3, 7, 7)), data=arr)
        assert v is not None

    def test_kind_is_initializer(self) -> None:
        """Returned Value must have INITIALIZER kind."""
        g = Graph()
        arr = np.zeros((10,), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)), data=arr)
        assert v.kind == ValueKind.INITIALIZER

    def test_data_stored(self) -> None:
        """The numpy array is stored on the Value."""
        g = Graph()
        arr = np.ones((3, 3), dtype=np.float64)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT64, shape=(3, 3)), data=arr)
        assert v.data is arr

    def test_tensor_type_stored(self) -> None:
        """The tensor type is stored on the Value."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        tt = TensorType(dtype=DType.FLOAT32, shape=(5,))
        v = g.add_initializer(tensor_type=tt, data=arr)
        assert v.tensor_type is tt

    def test_producer_is_none(self) -> None:
        """Initializer values have no producer."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        assert v.producer is None

    def test_name_preserved(self) -> None:
        """Optional name is stored on the Value."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr, name="weight_0")
        assert v.name == "weight_0"

    def test_registered_in_values(self) -> None:
        """Initializer is registered in the graph's value registry."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        assert g.value_count == 1

    def test_appended_to_initializers(self) -> None:
        """Initializer is appended to graph.initializers."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        assert v in g.initializers

    def test_not_in_inputs(self) -> None:
        """Initializer does not appear in graph.inputs."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        assert g.inputs == []

    def test_multiple_initializers(self) -> None:
        """Multiple initializers can be added."""
        g = Graph()
        w = g.add_initializer(
            tensor_type=TensorType(dtype=DType.FLOAT32, shape=(64, 3, 7, 7)),
            data=np.zeros((64, 3, 7, 7), dtype=np.float32),
            name="weight",
        )
        b = g.add_initializer(
            tensor_type=TensorType(dtype=DType.FLOAT32, shape=(64,)),
            data=np.zeros((64,), dtype=np.float32),
            name="bias",
        )
        assert len(g.initializers) == 2
        assert g.initializers[0] is w
        assert g.initializers[1] is b

    def test_auto_id(self) -> None:
        """Initializer gets an auto-generated id."""
        g = Graph()
        arr = np.zeros((5,), dtype=np.float32)
        v = g.add_initializer(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(5,)), data=arr)
        assert isinstance(v.id, str)
        assert len(v.id) > 0

    def test_initializer_usable_as_node_input(self) -> None:
        """An initializer Value can be used as a node input."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        w = g.add_initializer(
            tensor_type=TensorType(dtype=DType.FLOAT32, shape=(3, 4)),
            data=np.zeros((3, 4), dtype=np.float32),
        )
        node = g.make_node(
            op_type="MatMul",
            inputs=[inp, w],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2, 4))],
        )
        assert w.users[0] == (node, 1)
