"""Tests for protofx.ir.Graph — graph-owned mutable IR."""

import pytest

from protofx.ir import DType, TensorType
from protofx.ir.graph import Graph
from protofx.ir.value import ValueKind


class TestGraphConstruction:
    """Verify Graph can be constructed with expected fields."""

    def test_empty_graph(self) -> None:
        """An empty Graph has no inputs, outputs, or nodes."""
        g = Graph()
        assert g.inputs == []
        assert g.outputs == []
        assert g.nodes == []

    def test_name_default_none(self) -> None:
        """Graph name defaults to None."""
        g = Graph()
        assert g.name is None

    def test_name_set(self) -> None:
        """Graph name can be explicitly set."""
        g = Graph(name="main")
        assert g.name == "main"

    def test_parent_default_none(self) -> None:
        """Parent defaults to None for top-level graphs."""
        g = Graph()
        assert g.parent is None

    def test_parent_can_be_set(self) -> None:
        """Parent can be set to another Graph for subgraph support."""
        parent = Graph(name="outer")
        child = Graph(name="inner", parent=parent)
        assert child.parent is parent

    def test_values_registry_empty(self) -> None:
        """Internal value registry starts empty."""
        g = Graph()
        assert g.value_count == 0

    def test_node_count_empty(self) -> None:
        """Internal node count starts at zero."""
        g = Graph()
        assert g.node_count == 0


# ---------------------------------------------------------------------------
# Graph.add_input
# ---------------------------------------------------------------------------


class TestGraphAddInput:
    """Verify Graph.add_input creates and registers a GRAPH_INPUT Value."""

    def test_returns_value(self) -> None:
        """add_input must return a Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        assert v is not None

    def test_value_kind_is_graph_input(self) -> None:
        """Returned Value must have GRAPH_INPUT kind."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.kind == ValueKind.GRAPH_INPUT

    def test_value_has_auto_id(self) -> None:
        """Value id is auto-generated by Graph."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert isinstance(v.id, str)
        assert len(v.id) > 0

    def test_value_registered_in_inputs(self) -> None:
        """Value is appended to graph.inputs."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v in g.inputs

    def test_value_registered_in_values(self) -> None:
        """Value is registered in the internal value registry."""
        g = Graph()
        g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert g.value_count == 1

    def test_auto_id_increments(self) -> None:
        """Each add_input produces a distinct id."""
        g = Graph()
        v0 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        v1 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v0.id != v1.id

    def test_name_preserved(self) -> None:
        """Optional name is stored on the Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), name="input_0")
        assert v.name == "input_0"

    def test_producer_is_none(self) -> None:
        """Graph inputs have no producer."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.producer is None

    def test_users_empty(self) -> None:
        """Newly created input has no users."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.users == []


# ---------------------------------------------------------------------------
# Graph.make_node
# ---------------------------------------------------------------------------


class TestGraphMakeNode:
    """Verify Graph.make_node creates a Node with outputs and use-def links."""

    def test_returns_node(self) -> None:
        """make_node must return a Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2, 3))],
        )
        assert node is not None

    def test_node_has_auto_id(self) -> None:
        """Node id is auto-generated by Graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert isinstance(node.id, str)
        assert len(node.id) > 0

    def test_node_registered_in_nodes(self) -> None:
        """Node is appended to graph.nodes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert node in g.nodes

    def test_node_registered_in_registry(self) -> None:
        """Node is registered in the internal node registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert g.node_count == 1

    def test_outputs_created(self) -> None:
        """Node outputs are auto-created as Value instances."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(node.outputs) == 1
        assert node.outputs[0].kind == ValueKind.NODE_OUTPUT

    def test_output_producer_set(self) -> None:
        """Each output Value's producer must point to the created Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.outputs[0].producer is node

    def test_output_values_registered(self) -> None:
        """Output Values are registered in the graph's value registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        # 1 input + 1 output = 2 values
        assert g.value_count == 2

    def test_input_users_updated(self) -> None:
        """Creating a node updates users on each input Value."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(inp.users) == 1
        assert inp.users[0] == (node, 0)

    def test_multi_input_users(self) -> None:
        """Each input Value gets the correct (node, slot) entry."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, b], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert a.users[0] == (node, 0)
        assert b.users[0] == (node, 1)

    def test_multi_output_node(self) -> None:
        """A node with multiple outputs produces one Value per output."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)))
        node = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
            ],
        )
        assert len(node.outputs) == 2
        assert node.outputs[0].producer is node
        assert node.outputs[1].producer is node

    def test_node_inputs_reference(self) -> None:
        """node.inputs stores references to the input Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.inputs == [inp]

    def test_chained_nodes(self) -> None:
        """Output of one node can be input to another; use-def chain."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        assert n1.outputs[0].users[0] == (n2, 0)
        assert n2.inputs[0].producer is n1

    def test_attributes_forwarded(self) -> None:
        """Attributes are stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1, 3, 224, 224)))
        node = g.make_node(
            op_type="Conv",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1, 64, 112, 112))],
            attributes={"kernel_shape": [7, 7], "strides": [2, 2]},
        )
        assert node.attributes == {"kernel_shape": [7, 7], "strides": [2, 2]}

    def test_domain_forwarded(self) -> None:
        """Domain is stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="CustomOp",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            domain="com.custom",
        )
        assert node.domain == "com.custom"

    def test_name_forwarded(self) -> None:
        """Optional node name is stored."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            name="relu_0",
        )
        assert node.name == "relu_0"

    def test_output_names_forwarded(self) -> None:
        """Optional output names are stored on output Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
            output_names=["relu_out"],
        )
        assert node.outputs[0].name == "relu_out"


# ---------------------------------------------------------------------------
# Graph.set_node_inputs — atomic input rewiring
# ---------------------------------------------------------------------------


class TestGraphSetNodeInputs:
    """Verify set_node_inputs atomically rewires use-def links.

    Atomic order:
    1. Remove old users entries from old input Values.
    2. Replace node.inputs.
    3. Add new users entries to new input Values.
    """

    def test_basic_rewire(self) -> None:
        """Replace single input — old users cleared, new users added."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(node, [b])
        assert node.inputs == [b]
        assert len(a.users) == 0
        assert b.users[0] == (node, 0)

    def test_multi_input_rewire(self) -> None:
        """Replace both inputs of a binary op."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        c = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        d = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, b], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(node, [c, d])
        assert len(a.users) == 0
        assert len(b.users) == 0
        assert c.users[0] == (node, 0)
        assert d.users[0] == (node, 1)

    def test_rewire_preserves_other_users(self) -> None:
        """Rewiring one node does not affect another node using the same value."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(op_type="Sigmoid", inputs=[a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_node_inputs(n1, [b])
        # n2 still uses a
        assert any(u[0] is n2 for u in a.users)
        assert not any(u[0] is n1 for u in a.users)

    def test_same_value_multiple_slots(self) -> None:
        """A value used in multiple input slots gets entries for each."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, a], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(a.users) == 2
        g.set_node_inputs(node, [a])
        assert len(a.users) == 1
        assert a.users[0] == (node, 0)


# ---------------------------------------------------------------------------
# Graph.set_value_type — update tensor metadata
# ---------------------------------------------------------------------------


class TestGraphSetValueType:
    """Verify set_value_type updates tensor metadata on a Value."""

    def test_update_tensor_type(self) -> None:
        """Tensor type is replaced."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        new_tt = TensorType(dtype=DType.FLOAT16, shape=(2, 3))
        g.set_value_type(v, new_tt)
        assert v.tensor_type is new_tt

    def test_original_unchanged_reference(self) -> None:
        """The original TensorType object is not mutated."""
        g = Graph()
        original_tt = TensorType(dtype=DType.FLOAT32, shape=(2,))
        v = g.add_input(tensor_type=original_tt)
        new_tt = TensorType(dtype=DType.INT64, shape=(2,))
        g.set_value_type(v, new_tt)
        assert original_tt.dtype == DType.FLOAT32


# ---------------------------------------------------------------------------
# Graph.set_graph_outputs
# ---------------------------------------------------------------------------


class TestGraphSetGraphOutputs:
    """Verify set_graph_outputs sets graph.outputs properly."""

    def test_set_outputs(self) -> None:
        """Graph outputs are set to the provided values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_graph_outputs([node.outputs[0]])
        assert g.outputs == [node.outputs[0]]

    def test_set_multiple_outputs(self) -> None:
        """Multiple outputs can be set."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)))
        node = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
            ],
        )
        g.set_graph_outputs([node.outputs[0], node.outputs[1]])
        assert len(g.outputs) == 2

    def test_replace_outputs(self) -> None:
        """Setting outputs replaces previous outputs."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        g.set_graph_outputs([n1.outputs[0]])
        assert g.outputs == [n1.outputs[0]]
        g.set_graph_outputs([n2.outputs[0]])
        assert g.outputs == [n2.outputs[0]]


# ---------------------------------------------------------------------------
# Graph.remove_node — fast-fail if outputs in use
# ---------------------------------------------------------------------------


class TestGraphRemoveNode:
    """Verify remove_node deletes a node and cleans up use-def links."""

    def test_remove_unused_node(self) -> None:
        """Remove a node whose outputs have no consumers."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.remove_node(node)
        assert node not in g.nodes
        assert g.node_count == 0

    def test_remove_cleans_input_users(self) -> None:
        """Removing a node clears its entries from input Value users."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.remove_node(node)
        assert len(inp.users) == 0

    def test_remove_unregisters_output_values(self) -> None:
        """Removing a node unregisters its output Values from the graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert g.value_count == 2
        g.remove_node(g.nodes[0])
        assert g.value_count == 1

    def test_remove_refuses_if_output_in_use(self) -> None:
        """remove_node raises ValueError if any output has consumers."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        with pytest.raises(ValueError, match="in use"):
            g.remove_node(n1)

    def test_remove_refuses_preserves_state(self) -> None:
        """After a refused removal, the graph is unchanged."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        try:
            g.remove_node(n1)
        except ValueError:
            pass
        assert n1 in g.nodes
        assert g.node_count == 2


class TestGraphTopologicalSort:
    """Tests for Graph.topological_sort — Kahn's algorithm & cycle detection."""

    def test_empty_graph(self) -> None:
        """Topological sort on an empty graph returns an empty list."""
        g = Graph()
        assert g.topological_sort() == []

    def test_single_node(self) -> None:
        """Single-node graph returns that node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        result = g.topological_sort()
        assert result == [n1]

    def test_linear_chain(self) -> None:
        """Linear chain: A -> B -> C returns [A, B, C]."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        n3 = g.make_node(
            op_type="Tanh", inputs=[n2.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        result = g.topological_sort()
        assert result == [n1, n2, n3]

    def test_diamond_dag(self) -> None:
        """Diamond DAG: predecessors appear before dependents."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(op_type="Sigmoid", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n3 = g.make_node(
            op_type="Add",
            inputs=[n1.outputs[0], n2.outputs[0]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        result = g.topological_sort()
        # n3 must come after both n1 and n2
        assert result.index(n3) > result.index(n1)
        assert result.index(n3) > result.index(n2)
        assert len(result) == 3

    def test_returns_new_list(self) -> None:
        """topological_sort returns a freshly allocated list, not graph.nodes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        result = g.topological_sort()
        assert result is not g.nodes

    def test_cycle_detection_raises(self) -> None:
        """A graph with a cycle in Node inputs raises ValueError."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        # Force a cycle: make n1 depend on n2's output
        g.set_node_inputs(n1, [n2.outputs[0]])
        with pytest.raises(ValueError, match="cycle"):
            g.topological_sort()

    def test_multi_output_node_ordering(self) -> None:
        """Node with multiple outputs: dependents come after the producer."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(4,)))
        n_split = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,)), TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        n_a = g.make_node(
            op_type="Relu",
            inputs=[n_split.outputs[0]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        n_b = g.make_node(
            op_type="Sigmoid",
            inputs=[n_split.outputs[1]],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
        )
        result = g.topological_sort()
        assert result.index(n_split) < result.index(n_a)
        assert result.index(n_split) < result.index(n_b)


class TestGraphValidate:
    """Tests for Graph.validate — IR invariant checking."""

    def test_valid_graph_passes(self) -> None:
        """A correctly constructed graph passes validation."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        g.set_graph_outputs([n1.outputs[0]])
        g.validate()  # should not raise

    def test_empty_graph_passes(self) -> None:
        """An empty graph passes validation."""
        g = Graph()
        g.validate()  # should not raise

    def test_detects_broken_producer(self) -> None:
        """Fails if a node output's producer does not point back to the node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: set producer to None
        n1.outputs[0].producer = None
        with pytest.raises(ValueError, match="producer"):
            g.validate()

    def test_detects_broken_user_backref(self) -> None:
        """Fails if a value's users list is inconsistent with node.inputs."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: add a fake user entry
        from protofx.ir.node import Node

        fake_node = Node(id="fake", op_type="Fake", inputs=[], outputs=[])
        n1.outputs[0].users.append((fake_node, 0))
        with pytest.raises(ValueError, match="user"):
            g.validate()

    def test_detects_unregistered_input_value(self) -> None:
        """Fails if a node references an input value not in the graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        # Corrupt: replace input with an unregistered value
        from protofx.ir.value import Value

        rogue = Value(id="rogue", kind=ValueKind.GRAPH_INPUT, tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1.inputs[0] = rogue
        with pytest.raises(ValueError, match="not registered"):
            g.validate()

    def test_detects_cycle(self) -> None:
        """Validation catches cycles via topological sort."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        g.set_node_inputs(n1, [n2.outputs[0]])
        with pytest.raises(ValueError, match="cycle"):
            g.validate()
