"""Tests for protofx.ir.Graph — graph-owned mutable IR."""

import pytest

from protofx.ir import DType, TensorType
from protofx.ir.graph import Graph
from protofx.ir.value import ValueKind


class TestGraphConstruction:
    """Verify Graph can be constructed with expected fields."""

    def test_empty_graph(self) -> None:
        """An empty Graph has no inputs, outputs, or nodes."""
        g = Graph()
        assert g.inputs == []
        assert g.outputs == []
        assert g.nodes == []

    def test_name_default_none(self) -> None:
        """Graph name defaults to None."""
        g = Graph()
        assert g.name is None

    def test_name_set(self) -> None:
        """Graph name can be explicitly set."""
        g = Graph(name="main")
        assert g.name == "main"

    def test_parent_default_none(self) -> None:
        """Parent defaults to None for top-level graphs."""
        g = Graph()
        assert g.parent is None

    def test_parent_can_be_set(self) -> None:
        """Parent can be set to another Graph for subgraph support."""
        parent = Graph(name="outer")
        child = Graph(name="inner", parent=parent)
        assert child.parent is parent

    def test_values_registry_empty(self) -> None:
        """Internal value registry starts empty."""
        g = Graph()
        assert g.value_count == 0

    def test_node_count_empty(self) -> None:
        """Internal node count starts at zero."""
        g = Graph()
        assert g.node_count == 0


# ---------------------------------------------------------------------------
# Graph.add_input
# ---------------------------------------------------------------------------


class TestGraphAddInput:
    """Verify Graph.add_input creates and registers a GRAPH_INPUT Value."""

    def test_returns_value(self) -> None:
        """add_input must return a Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        assert v is not None

    def test_value_kind_is_graph_input(self) -> None:
        """Returned Value must have GRAPH_INPUT kind."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.kind == ValueKind.GRAPH_INPUT

    def test_value_has_auto_id(self) -> None:
        """Value id is auto-generated by Graph."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert isinstance(v.id, str)
        assert len(v.id) > 0

    def test_value_registered_in_inputs(self) -> None:
        """Value is appended to graph.inputs."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v in g.inputs

    def test_value_registered_in_values(self) -> None:
        """Value is registered in the internal value registry."""
        g = Graph()
        g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert g.value_count == 1

    def test_auto_id_increments(self) -> None:
        """Each add_input produces a distinct id."""
        g = Graph()
        v0 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        v1 = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        assert v0.id != v1.id

    def test_name_preserved(self) -> None:
        """Optional name is stored on the Value."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)), name="input_0")
        assert v.name == "input_0"

    def test_producer_is_none(self) -> None:
        """Graph inputs have no producer."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.producer is None

    def test_users_empty(self) -> None:
        """Newly created input has no users."""
        g = Graph()
        v = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        assert v.users == []


# ---------------------------------------------------------------------------
# Graph.make_node
# ---------------------------------------------------------------------------


class TestGraphMakeNode:
    """Verify Graph.make_node creates a Node with outputs and use-def links."""

    def test_returns_node(self) -> None:
        """make_node must return a Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2, 3)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2, 3))],
        )
        assert node is not None

    def test_node_has_auto_id(self) -> None:
        """Node id is auto-generated by Graph."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert isinstance(node.id, str)
        assert len(node.id) > 0

    def test_node_registered_in_nodes(self) -> None:
        """Node is appended to graph.nodes."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert node in g.nodes

    def test_node_registered_in_registry(self) -> None:
        """Node is registered in the internal node registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        assert g.node_count == 1

    def test_outputs_created(self) -> None:
        """Node outputs are auto-created as Value instances."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(node.outputs) == 1
        assert node.outputs[0].kind == ValueKind.NODE_OUTPUT

    def test_output_producer_set(self) -> None:
        """Each output Value's producer must point to the created Node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.outputs[0].producer is node

    def test_output_values_registered(self) -> None:
        """Output Values are registered in the graph's value registry."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))])
        # 1 input + 1 output = 2 values
        assert g.value_count == 2

    def test_input_users_updated(self) -> None:
        """Creating a node updates users on each input Value."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert len(inp.users) == 1
        assert inp.users[0] == (node, 0)

    def test_multi_input_users(self) -> None:
        """Each input Value gets the correct (node, slot) entry."""
        g = Graph()
        a = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        b = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Add", inputs=[a, b], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert a.users[0] == (node, 0)
        assert b.users[0] == (node, 1)

    def test_multi_output_node(self) -> None:
        """A node with multiple outputs produces one Value per output."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(10,)))
        node = g.make_node(
            op_type="Split",
            inputs=[inp],
            output_types=[
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
                TensorType(dtype=DType.FLOAT32, shape=(5,)),
            ],
        )
        assert len(node.outputs) == 2
        assert node.outputs[0].producer is node
        assert node.outputs[1].producer is node

    def test_node_inputs_reference(self) -> None:
        """node.inputs stores references to the input Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        assert node.inputs == [inp]

    def test_chained_nodes(self) -> None:
        """Output of one node can be input to another; use-def chain."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        n1 = g.make_node(op_type="Relu", inputs=[inp], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))])
        n2 = g.make_node(
            op_type="Sigmoid", inputs=[n1.outputs[0]], output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))]
        )
        assert n1.outputs[0].users[0] == (n2, 0)
        assert n2.inputs[0].producer is n1

    def test_attributes_forwarded(self) -> None:
        """Attributes are stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1, 3, 224, 224)))
        node = g.make_node(
            op_type="Conv",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1, 64, 112, 112))],
            attributes={"kernel_shape": [7, 7], "strides": [2, 2]},
        )
        assert node.attributes == {"kernel_shape": [7, 7], "strides": [2, 2]}

    def test_domain_forwarded(self) -> None:
        """Domain is stored on the created node."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="CustomOp",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            domain="com.custom",
        )
        assert node.domain == "com.custom"

    def test_name_forwarded(self) -> None:
        """Optional node name is stored."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(1,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(1,))],
            name="relu_0",
        )
        assert node.name == "relu_0"

    def test_output_names_forwarded(self) -> None:
        """Optional output names are stored on output Values."""
        g = Graph()
        inp = g.add_input(tensor_type=TensorType(dtype=DType.FLOAT32, shape=(2,)))
        node = g.make_node(
            op_type="Relu",
            inputs=[inp],
            output_types=[TensorType(dtype=DType.FLOAT32, shape=(2,))],
            output_names=["relu_out"],
        )
        assert node.outputs[0].name == "relu_out"
