"""Generate an opset compatibility matrix from the live op handler registry.

Produces a markdown table with ops as rows and ONNX opset versions 11-21
as columns. Supported versions show a check mark, unsupported show a dash.

Usage::

    python -m scripts.gen_opset_matrix
    python -m scripts.gen_opset_matrix --output docs/dev/OPSET_COMPATIBILITY.md
"""

from __future__ import annotations

import argparse
import sys

_MIN_OPSET = 11
_MAX_OPSET = 21


def generate_opset_matrix() -> str:
    """Generate a markdown opset compatibility matrix from the live registry.

    Returns:
        A markdown string containing the compatibility table.
    """
    from protofx.ops._registry import list_registry

    registry = list_registry()

    # Filter out test-only registrations (prefixed with _)
    ops = {k: v for k, v in sorted(registry.items()) if not k.startswith("_")}

    opset_range = range(_MIN_OPSET, _MAX_OPSET + 1)
    header_cols = " | ".join(str(v) for v in opset_range)
    header = f"| Op | {header_cols} |"
    separator = "|" + "---|" * (len(opset_range) + 1)

    lines: list[str] = [
        "<!-- Auto-generated by scripts/gen_opset_matrix.py — do not edit manually -->",
        f"<!-- Regenerate: python -m scripts.gen_opset_matrix --output {_OUTPUT_DEFAULT} -->",
        "",
        "# Opset Compatibility Matrix",
        "",
        header,
        separator,
    ]

    for op_name, op_range in ops.items():
        cells: list[str] = []
        for v in opset_range:
            if op_range is not None and op_range[0] <= v <= op_range[1]:
                cells.append("\u2705")
            else:
                cells.append("-")
        row = f"| {op_name} | {' | '.join(cells)} |"
        lines.append(row)

    lines.append("")
    return "\n".join(lines)


_OUTPUT_DEFAULT = "docs/dev/OPSET_COMPATIBILITY.md"


def main() -> None:
    """CLI entry point for opset matrix generation."""
    parser = argparse.ArgumentParser(description="Generate opset compatibility matrix")
    parser.add_argument(
        "--output",
        default=None,
        help=f"Write output to file (default: stdout). Suggested: {_OUTPUT_DEFAULT}",
    )
    args = parser.parse_args()

    matrix = generate_opset_matrix()

    if args.output:
        with open(args.output, "w") as f:
            f.write(matrix)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(matrix)


if __name__ == "__main__":
    main()
